"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.ERROR_NOTADMIN = exports.ERROR_INVALID_FORMAT = exports.ERROR_COMMENT_NOT_MATCHED = exports.ERROR_PROJECT_NOT_MATCHED = exports.ERROR_NO_PROJECTID = exports.ERROR_USER_NOT_OWNER = exports.ERROR_NO_EXISTING_PROJECT = exports.ERROR_INVALID_PROJECTID_FORMAT = exports.ERROR_UNAUTHENTICATED = exports.ERROR_SQL = void 0;
var ERROR_SQL = -1;
exports.ERROR_SQL = ERROR_SQL;
var ERROR_UNAUTHENTICATED = 1;
exports.ERROR_UNAUTHENTICATED = ERROR_UNAUTHENTICATED;
var ERROR_INVALID_PROJECTID_FORMAT = 9;
exports.ERROR_INVALID_PROJECTID_FORMAT = ERROR_INVALID_PROJECTID_FORMAT;
var ERROR_NO_EXISTING_PROJECT = 5;
exports.ERROR_NO_EXISTING_PROJECT = ERROR_NO_EXISTING_PROJECT;
var ERROR_USER_NOT_OWNER = 6;
exports.ERROR_USER_NOT_OWNER = ERROR_USER_NOT_OWNER;
var ERROR_NO_PROJECTID = 7;
exports.ERROR_NO_PROJECTID = ERROR_NO_PROJECTID;
var ERROR_PROJECT_NOT_MATCHED = 10;
exports.ERROR_PROJECT_NOT_MATCHED = ERROR_PROJECT_NOT_MATCHED;
var ERROR_COMMENT_NOT_MATCHED = 11;
exports.ERROR_COMMENT_NOT_MATCHED = ERROR_COMMENT_NOT_MATCHED;
var ERROR_INVALID_FORMAT = 12;
exports.ERROR_INVALID_FORMAT = ERROR_INVALID_FORMAT;
var ERROR_NOTADMIN = 13;
exports.ERROR_NOTADMIN = ERROR_NOTADMIN;